insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Bereishit", "בראשית");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Noach", "נח");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Lech Lecha", "לך לך");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayera", "וירא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Chayei Sara", "חיי שרה");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Toldot", "תולדות");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayeitze", "ויצא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayishlach", "וישלח");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayeshev", "וישב");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Miketz", "מקץ");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayigash", "ויגש");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayechi", "ויחי");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Shmot", "שמות");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Va'era", "וארא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Bo", "בא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Beshalach", "בשלח");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Yitro", "יתרו");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Mishpatim", "משפטים");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Truma", "תרומה");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Tetzave", "תצוה");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Ki Tisa", "כי תשא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayakhel", "ויקהל");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Pekudei", "פקודי");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayikra", "ויקרא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Tzav", "צו");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Shmini", "שמיני");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Tazria", "תזריע");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Metzora", "מצורע");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Acharei Mot", "אחרי מות");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Kedoshim", "קדושים");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Emor", "אמור");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Behar", "בהר");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Bechukotai", "בחוקותי");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Bamidbar", "במדבר");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Naso", "נשא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Beha'alotch", "בהעלותך");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Shlach", "שלח");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Korach", "קרח");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Chukat", "חוקת");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Balak", "בלק");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Pinchas", "פנחס");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Matot", "מטות");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Masei", "מסעי");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Dvarim", "דברים");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Va'etchanan", "ואתחנן");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Eikev", "עקב");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Re'eh", "ראה");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Shoftim", "שופטים");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Ki Tetze", "כי תצא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Ki Tavo", "כי תבוא");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Nitzavim", "ניצבים");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vayelech", "וילך");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Ha'azinu", "האזינו");
insert into v1uowltzsrujmj9s.parasha (english_name, hebrew_name) values ("Vezot Habracha", "וזאת הברכה");